### ISSUE TITLE
Discuss meaningful variable names

### ISSUE THREAD

**Issue by qethanm** [Datapolitan-Training/data-analysis-python#102]
When introducing variables, consider one or both of:

1. discussing the use of meaningful variable names
2. modifying the sample code to use meaningful variable names

Nothing super-long, but mildly more descriptive than `df` or `a`/`b`/`c` . 

- This will help with debugging (which can already be painful for people who are learning)
- For folks who are new to both programming and Pandas, they may assume that every DataFrame must be named `df` (and then what happens if they want to have two DataFrames?) ...

http://training.datapolitan.com/data-analysis-python/#76

**Comment by datapolitan** [comment]
@qethanm I like this. The one thing I'll say is that I emphasize that we use `df` because it's in the documentation. I think it's a good thing to align with the what they're likely to see when they dive into the material, but I also try an emphasize that they can name the dataframes anything that makes sense for what they're doing. Happy to hear what others have to say about this. My emphasis is on clarity and lack of confusion, but I also want them to be empowered to make the code their own whenever possible.

**Comment by justalfred** [comment]
Thought about this more. Let me try this compromise: Edit the `a+b` example to use descriptive variable names to normalize that practice. Leave the `df` references to normalize that convention. Encourage them to use descriptive names in their own notebooks like `df_faithful`. If I find that people still stick to `df`, then we can talk about refactoring the sample code more extensively.
