### ISSUE TITLE
Add the outcome of analysis for the Today's Analysis slide

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#54]
Give them the sense of what we're going to create today

**Comment by justalfred** [comment]
Hmm, I remember suggesting this, but since we end with a free-form exercise, now I don't know what the outcome is that we should tease with. So I'll just put some examples of the questions they'll answer along the way and we'll see how that lands. For now, in this slide, I'll put the following at the end:
* What borough generates the most complaints?
* What department gets the most complaints?
* What does this look like?

**Comment by datapolitan** [comment]
Sounds good @justalfred.
