### ISSUE TITLE
Move derelict vehicles example to the fuzzy match slide

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#78]
See if it stays with new class, but might not resonate

**Comment by datapolitan** [comment]
Pull it

**Comment by justalfred** [comment]
I think I want to try this one more time before pulling it.

**Comment by datapolitan** [comment]
@justalfred Sounds good to me. It feels awkward to me but we can make it work. Another possibility is to move it closer to the actual work with derelict vehicles in code.

**Comment by justalfred** [comment]
Yeah, I guess to expand on my thinking a little further, this seems like the end goal of introducing the `str` accessor which is why I'm reluctant to pull it. Pulling this means pulling the whole fuzzy matching section, and I think people do ask about that. Maybe we can introduce `dt` stuff instead? Address #65 deliberately instead of only if people ask?

I'm curious what makes this moment feel awkward. I might have forgotten or missed it.

**Comment by ebrelsford** [comment]
I think this is working fine with the current sequence.
