### ISSUE TITLE
Add navigating the notebook

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/data-analysis-python#84]
+ Adding row
+ Rearranging rows
+ Cutting rows

**Comment by datapolitan** [comment]
@justalfred this is just a placeholder for adding some explicit content around the options in Jupyter and not necessarily a needed fix.

**Comment by justalfred** [comment]
I think this is important, so I'll add it. I'll add to your list a note on waiting for a cell to finish running, and making sure the cell type is 'code'. And I'll put a speaker note for the instructors (me) to use the same interface elements as the students instead of flying past them with keyboard shortcuts.

**Comment by datapolitan** [comment]
Sounds good. It's okay as we go through to do more with less explaining, but also, don't try to explain too much in the beginning. There's only so much detail people can take in without practice and context. In some of these cases, people just have to ask if it's not clear and we need to be willing to stop and explain.

**Comment by justalfred** [comment]
That's a good reminder. I'll skip past that slide and say something like, "Here are some more tips for other things you might want to do. But have a go at it yourselves and get comfortable with the interface. You can come back to this slide if you get stuck." Or maybe I can move it to the end and link to it the way we have the the key pandas functions at the end. Any thoughts?
